### ISSUE TITLE
Auto-indentation places cursor in the wrong spot

### ISSUE THREAD

**Issue by peterhoeg** [matthewbauer/nix-mode#1]
First of all, this works WAY better than upstream.

I noticed one issue with auto-indenting though.

Let's say on on a line that is indented. Hitting "o" or "O" (I'm using evil) to create a new line below/above also adds the indentation but the cursor is placed BEFORE the spaces.

Below, | is my cursor.

``` nix
{
  a = "";|
}
```

Hitting "o" gives me ```"|  "``` instead of ```"  |"``` (the quotation marks are only there to highlight the spaces). I can see the spaces are there but trailing the cursor.

``` nix
{
  a = "";
|
}
```

**Comment by peterhoeg** [comment]
Sorry, still doesn't do it. Now the trailing spaces are gone, but the cursor still starts at column 0.

**Comment by matthewbauer** [comment]
I'm still not able to reproduce this. I'll look into it a little more but I'm kind of lost.

Right now, I'm using "indent-line-to" to indent everything. Perhaps there's something else that can be used.

**Comment by peterhoeg** [comment]
This has been solved in master - I don't know which commit, sorry.
