### ISSUE TITLE
Indentation bug

### ISSUE THREAD

**Issue by taktoa** [matthewbauer/nix-mode#10]
If you leave out the hash at the end of line 29 in [this file](https://gist.github.com/taktoa/e58575cce66e77f44cadd83cdda94fa5), the lines after it will indent, which is very strange, considering that line 29 is itself commented.

I suspect the indentation tokenizer is failing to ignore commented-out `let` keywords (though that doesn't really explain why adding the hash at the end of the line fixes it).

**Comment by matthewbauer** [comment]
Yeah indentation is still very buggy. There aren't very good rules in Nix for it, so I kind of am debugging as these come up.
