### ISSUE TITLE
Incorrect indentation for let

### ISSUE THREAD

**Issue by peterhoeg** [matthewbauer/nix-mode#2]
The proper indentation for the let statement is:

``` nix
let
  foo = "bar";
```

But nix-mode will indent like this:
``` nix
let
foo = "bar";
```

**Comment by matthewbauer** [comment]
This is on my todo list, but it's not as easy as just counting "lets" and "ins" because they're allowed to be inline as well.

**Comment by matthewbauer** [comment]
Fixed in master

**Comment by peterhoeg** [comment]
Let me know if you want a different issue for this, but the ```let``` fixes seem to have broken indentation of imports.

What I got:

``` nix
imports = [
   ./a.nix
     ./b.nix
     ./c.nix
     ];
```

What I expected:

``` nix
 imports = [
   ./a.nix
   ./b.nix
   ./c.nix
 ];
```
