### ISSUE TITLE
nix-mode slow with all-packages

### ISSUE THREAD

**Issue by matthewbauer** [matthewbauer/nix-mode#23]

**Comment by ljli** [comment]
I also had this problem today. Not sure if it has the same cause.
When I enter a new line in all-packages.nix emacs freezes for ~4 seconds. The profiler says most of the time (~80%) is spent in `syntax-ppss` called from `nix-indent-level-let`.
Some ideas:
I see we're using `syntax-ppss` to detect comments, maybe we could check the `face` property instead? That would probably be faster.
`nix-indent-level-let` seems to iterate over the whole file in this case, maybe we don't have to do that?

**Comment by matthewbauer** [comment]
Yeah most emacs modes do indentation relative to previous line. Nix-mode is trying to do it absolutely. I thought it would be better so one wrongly indented line doesn't mess the rest of it. Looks like some issues with it though. Feel free to tweak it if you want.

**Comment by Ericson2314** [comment]
I'd prefer relative indent too: it makes editing existing code that may be indented oddly easier.

**Comment by andir** [comment]
Just came across this as I had massive issues with `all-packages.nix`. I defined a custom mode derived from the nix-mode that had a couple of things disabled.

```
;; all-packages.nix wrecks emacs if the nix-mode plugin is used so use a derived mode for that
(define-derived-mode nix-all-packages-mode nix-mode "nix-all-packages"
  "all-packages.nix mode"
  (setq-local nix-mode-use-smie nil)
  (setq-local indent-line-function nil)
  (setq-local indent-tabs-mode nil)
  (setq-local lsp-lens-enable nil)
)
(add-to-list 'auto-mode-alist '("all-packages\\.nix\\'" . nix-all-packages-mode))
```
