### ISSUE TITLE
Syntax highlighting for ${..} attributes not working

### ISSUE THREAD

**Issue by teh** [matthewbauer/nix-mode#3]
First, thanks for doing this! This mode is so much better than the various hacks I had accumulated on top of the official mode.

I have a minor, low priority issue that's easily fixed by adding "" quotation marks:

```
    users.extraGroups.${promGroup}.gid = config.ids.gids.prometheus;
      users.extraUsers.${promUser} = {}
```

doesn't pick up the closing }, and continues highlighting the rest of the text with the same colour as `promGroup`.

**Comment by peterhoeg** [comment]
Adding cross reference: https://github.com/NixOS/nix/issues/1055

**Comment by matthewbauer** [comment]
This should be fixed in master. Give me a heads up if it's not.

**Comment by teh** [comment]
This does indeed work, man thanks!
