### ISSUE TITLE
Indentation is still off

### ISSUE THREAD

**Issue by peterhoeg** [matthewbauer/nix-mode#5]
This is using the latest master.

If run auto-indent on this:

```nix
{
  network = {
    description = "Some Network";
  };

  machineA = { config, pkgs, ... }: {
    imports = [ ./machines/machine_A.nix {} ];
  };
}
```

You get:

``` nix
{
  network = {
  description = "Some Network";
};

  machineA = { config, pkgs, ... }: {
  imports = [ ./machines/machine_A.nix {} ];
};
}
```

**Comment by matthewbauer** [comment]
That has to do with the '{' starting the file. If you add a new line to the front of  the file it should still work. I think I've added a fix for this any way. Let me know if it's still an issue.

**Comment by peterhoeg** [comment]
Works in master, thanks!
