### ISSUE TITLE
File starting with "{" breaks indentation. 

### ISSUE THREAD

**Issue by teh** [matthewbauer/nix-mode#8]
How to reproduce:

Use the following empty nix file:

```
{
  a = {
};
}
```

and try to indent the `};` line. I'd expect it to be indented by 2 but it's stuck at 0.

**Comment by matthewbauer** [comment]
Can you confirm this is on the latest version? I recall this being an issue at one point but I thought we had it fixed.

**Comment by teh** [comment]
Apologies, I seem to have missed an update. This works now, thanks!
