### ISSUE TITLE
Indent and syntax highlighting broken for ${..}

### ISSUE THREAD

**Issue by teh** [matthewbauer/nix-mode#9]
Hi, I am on master  (fa7a4a0d4dec563702fc27eb6d46b5546565278c) and I'm hitting two issues that I suspect are related:

1st - the indent after a ${...} in a string doesn't go back to 0:

```
{
  a = "${hello}";
  } # <-- doesn't move back to indent 0
```

2nd: syntax highlighting treats the last line as a string:

```
{
  a = "${hello}";
} // { b = 10; }
```

**Comment by teh** [comment]
AFAICT there is no simple fix. What we'd need is antiquotation to have both the `(` and the `|` property.

```elisp
(defun nix-syntax-propertize-close-brace ()
  "Set syntax properties for close braces.
If a close brace `}' ends an antiquote, the next character begins a string."
  (let* ((start (match-beginning 0))
         (context (save-excursion (save-match-data (syntax-ppss start))))
         (open (nth 1 context)))

    (when open ;; a corresponding open-brace was found
      (when (get-text-property open 'nix-syntax-antiquote)
        (put-text-property start (+ 1 start)
                           'syntax-table (string-to-syntax "|"))
	(put-text-property start (+ 1 start)
			   'syntax-table (string-to-syntax ")"))
	(put-text-property start (+ 1 start)
			   'nix-syntax-antiquote t)))))
```

**Comment by matthewbauer** [comment]
Ok, I think that @ljli has fixed this. Can you verify that those changes are good?

**Comment by teh** [comment]
Seems to mostly work, thanks!

**Comment by matthewbauer** [comment]
Awesome1

**Comment by Ericson2314** [comment]
`"${null}" asdf` messes up (string literal doesn't end). Adding a character between `}` and `"` fixes.

**Comment by matthewbauer** [comment]
See https://github.com/matthewbauer/nix-mode/pull/13#issuecomment-289954158

**Comment by Ericson2314** [comment]
Err, I am testing on latest master.

**Comment by matthewbauer** [comment]
Sorry, I wasn't clear:

I had the same problem that you are describing and it was fixed by running this:

```nix
(makunbound 'nix-mode-syntax-table)
```

And reloading the new nix-mode. The problem seems to be from having already loaded the earlier nix-mode that has the bad syntax table.

**Comment by Ericson2314** [comment]
Worked! Thanks, and sorry for missing that.
